<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-30T20:27:26 IST" name="Demo" finished-at="2024-04-30T20:28:52 IST" duration-ms="85498">
    <groups>
    </groups>
    <test started-at="2024-04-30T20:27:26 IST" name="LoginTest_Sanity" finished-at="2024-04-30T20:27:58 IST" duration-ms="32012">
      <class name="com.Sanity.tests.LoginTest">
        <test-method signature="userLogin()[pri:1, instance:com.Sanity.tests.LoginTest@316bcf94]" started-at="2024-04-30T20:27:26 IST" name="userLogin" finished-at="2024-04-30T20:27:58 IST" duration-ms="31986" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userLogin -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.Sanity.tests.LoginTest@316bcf94]" started-at="2024-04-30T20:27:58 IST" name="getResult" finished-at="2024-04-30T20:27:58 IST" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=userLogin status=SUCCESS method=LoginTest.userLogin()[pri:1, instance:com.Sanity.tests.LoginTest@316bcf94] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- com.Sanity.tests.LoginTest -->
    </test> <!-- LoginTest_Sanity -->
    <test started-at="2024-04-30T20:27:58 IST" name="ItemEdit_Sanity" finished-at="2024-04-30T20:28:52 IST" duration-ms="53456">
      <class name="com.Sanity.tests.EditItemTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.Sanity.tests.EditItemTest@130c12b7]" started-at="2024-04-30T20:27:25 IST" name="setUp" finished-at="2024-04-30T20:27:26 IST" duration-ms="1525" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="EditItem()[pri:1, instance:com.Sanity.tests.EditItemTest@130c12b7]" started-at="2024-04-30T20:27:58 IST" name="EditItem" finished-at="2024-04-30T20:28:52 IST" duration-ms="53454" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Sanity.tests.EditItemTest.EditItem(EditItemTest.java:205)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EditItem -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.Sanity.tests.EditItemTest@130c12b7]" started-at="2024-04-30T20:28:52 IST" name="getResult" finished-at="2024-04-30T20:28:52 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=EditItem status=FAILURE method=EditItemTest.EditItem()[pri:1, instance:com.Sanity.tests.EditItemTest@130c12b7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.Sanity.tests.EditItemTest@130c12b7]" started-at="2024-04-30T20:28:52 IST" name="tearDown" finished-at="2024-04-30T20:28:52 IST" duration-ms="552" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Sanity.tests.EditItemTest -->
    </test> <!-- ItemEdit_Sanity -->
  </suite> <!-- Demo -->
</testng-results>
